
---
- hosts: all
  connection: network_cli
  gather_facts: false
  tasks:  
  - name: продовжуємо
    routeros_command:
      commands:
# Вимикаємо адмін 
        - /user disable admin
# Відкриваємо порти 222 та 80 (80 для лабораторних виключно)
        - /ip firewall filter add chain=input protocol=tcp dst-port=222 action=accept in-interface=ether1
        - /ip firewall filter add chain=input protocol=tcp dst-port=80 action=accept in-interface=ether1
# Робимо маскарадінг
        - /ip firewall nat add chain=srcnat action=masquerade out-interface=ether1
# Налаштуванная файрвол
        - /ip firewall filter add action=accept chain=input comment= "defconf: accept established,related,untracked" connection-state=established,related,untracked
        - /ip firewall filter add action=drop chain=input comment="defconf: drop invalid" connection-state=invalid
        - /ip firewall filter add action=accept chain=input comment="defconf: accept ICMP" protocol=icmp
        - /ip firewall filter add action=drop chain=input comment="defconf: drop all not coming from ether1" in-interface=ether1
        - /ip firewall filter add action=accept chain=forward comment="defconf: accept established,related, untracked" connection-state=established,related,untracked
        - /ip firewall filter add action=drop chain=forward comment="defconf: drop invalid" connection-state=invalid
        - /ip firewall filter add action=drop chain=forward comment="defconf: drop all from WAN not DSTNATed" connection-nat-state=!dstnat connection-state=new in-interface=ether1
# Годинник
        - /system clock set time-zone-name=Europe/Kiev
  - name: debug print
    debug: var=adre_print.stdout_lines
