
---
- hosts: all
  connection: network_cli
  gather_facts: false
  tasks:  
  - name: Display oid value
    community.network.routeros_command:
      commands: 
        - / tool snmp-get community=spa oid=.1.3.6.1.4.1.14988.1.1.7.6.0 address=127.0.0.1
        - / tool snmp-get community=spa oid=.1.3.6.1.2.1.31.1.1.1.11.1 address=127.0.0.1      
    register: routeros_resources
  - debug: msg="{{ routeros_resources }}"
  - debug: msg="{{ routeros_resources.stdout_lines }}"
