---
- hosts: all
  tasks:
  - name: info
    shell: echo  "`date & hostname`" > /home/$USER/Desktop/info.txt
  - name: info2
    shell: echo  "Привіт, Сергій!" >> /home/$USER/Desktop/info.txt
  - name: debug print
    debug: var=ansible_facts['user_id']
#    debug: var=adre_print.stdout_lines
