---
- hosts: all
  become: true
  tasks:
  - name: specify 
    community.general.nmcli:
      conn_name: my-eth1
      ifname: enp3s0
      type: ethernet
      ip4: 192.168.88.21/24
      gw4: 192.168.88.1
      state: present
