---
- hosts: all
  become: true
  tasks:
  - name: Install needed network manager libs
    ansible.builtin.package:
      name:
#        - NetworkManager-libnm
        - nm-connection-editor
        - libsemanage-python
        - policycoreutils-python
      state: present
