
---
- hosts: all
  connection: network_cli
  gather_facts: false
  tasks:  
  - name: group add
    routeros_command:
      commands:
        - /ip firewall address-list add list=torrent_limit address=192.0.34.166/24
    register: adre_print
  - name: debug print
    debug: var=adre_print.stdout_lines
