
---
- hosts: all
  connection: network_cli
  gather_facts: false
  tasks:  
  - name: packet limit
    routeros_command:
      commands:
        - /ip firewall filter add chain=forward action=add-dst-to-address-list protocol=udp dst-address=192.168.88.2-192.168.88.254 address-list=dst_list address-list-timeout=0s
# 250 означает количество пакетов в секунду, разрешенное каждому клиенту
        - /ip firewall filter add chain=forward action=accept dst-address-list=dst_list dst-limit=250,250,dst-address/1m40s
        - /ip firewall filter add chain=forward action=reject reject-with=icmp-admin-prohibited dst-address-list=dst_list
       
    register: adre_print
  - name: debug print
    debug: var=adre_print.stdout_lines
