
---
- hosts: all
  connection: network_cli
  gather_facts: false
  tasks:  
  - name: torrent limit 1 user
    routeros_command:
      commands:
        - /ip firewall filter add chain=forward action=drop tcp-flags=syn protocol=tcp src-address=10.0.0.23 dst-port=!80,443,8080 connection-limit=40,32 
        - /ip firewall filter add chain=forward action=drop protocol=udp src-address=10.0.0.23 connection-limit=40,32
    register: adre_print
  - name: debug print
    debug: var=adre_print.stdout_lines
