- hosts: all
  tasks:
  - name: get-disc
    raw: Get-EventLog -Logname 'System'
    register: syserr

  - debug: msg="{{ syserr.stdout }}"
  - debug: msg=all
  - debug: msg="{{ syserr.stdout_lines }}"

