---
- name: Add a user
  hosts: all
  gather_facts: false
  tasks:
    - name: Add User
      win_user:
        name: spa
        password: "0993676664"
        state: present
        groups:
          - Пользователи
          - Пользователи удаленного рабочего стола

