---                                                                                                                                   
- hosts: all
  become: true
  tasks:      
  - nmcli:
      conn_name: "connection"
      type: ethernet
      dns4: "1.1.1.1"
      gw4: "192.168.88.1"
      ifname: "enp3s0"
      ip4: "192.168.88.26/24"
      state: present
